import fs from 'node:fs';
import assert from 'node:assert/strict';
const js = fs.readFileSync('site.js', 'utf8');
const css = fs.readFileSync('styles.css', 'utf8');
const model = fs.readFileSync('model.html', 'utf8');
const legacy = fs.readFileSync('content/posts/8198.html', 'utf8');
const home = fs.readFileSync('index.html', 'utf8');
const text = '可加微信“chuyimeishu01”，备注“模型资源”入群！';
assert.ok(js.includes(text));
assert.ok(js.includes('.detail-page, .legacy-detail'));
assert.ok(js.includes('getElementById("model-community-cta")'));
assert.ok(js.includes('/ouart-model-site/assets/shared/wechat-model-group-qr.png'));
assert.ok(js.includes('扫码添加微信，备注模型资源入群'));
assert.ok(css.includes('.model-community-cta'));
assert.ok(css.includes('width: 220px'));
assert.ok(css.includes('width: 180px'));
assert.ok(model.includes('class="detail-page"'));
assert.ok(legacy.includes('class="legacy-detail"'));
assert.ok(!home.includes('model-community-cta'));
assert.ok(fs.statSync('assets/shared/wechat-model-group-qr.png').size > 0);
console.log('community CTA focused static tests: PASS');
