import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';

const root=path.resolve(import.meta.dirname,'..');
const modelsText=fs.readFileSync(path.join(root,'data/models.js'),'utf8');
const sandbox={window:{}}; vm.runInNewContext(modelsText,sandbox);
const models=sandbox.window.OUART_MODELS;
const sitting=models.find(x=>x.id==='sitting-ghost');
const axe=models.find(x=>x.id==='axe-3d-print-model');
assert.ok(sitting);
assert.equal(sitting.sections.length,5);
assert.deepEqual([...sitting.sections.slice(0,4).map(x=>x.title)],['设计观察','打印与制作','涂装方向','场景应用']);
assert.equal(sitting.gallery.length,3);
assert.ok(sitting.gallery.every(x=>x.label==='场景应用示意图｜AI生成' && x.src.endsWith('.png')));
assert.equal(sitting.authorLicense.author,'Jaroslav_g');
assert.equal(sitting.authorLicense.license,'CC BY-SA 3.0');
const forbiddenLong='原始作品页面同时指向 Thingiverse，按 CC BY-SA 3.0 许可再分发。OUART 版本仅进行文件规范化、打包和署名说明整理；使用与再分发时请保留作者署名、来源和相同许可。';
assert.ok(!sitting.intro.includes(forbiddenLong));
assert.ok(!JSON.stringify(sitting.sections).includes(forbiddenLong));
assert.ok(axe && !axe.sections && !axe.gallery && !axe.authorLicense);
const site=fs.readFileSync(path.join(root,'site.js'),'utf8');
assert.match(site,/Array\.isArray\(model\.sections\)/);
assert.match(site,/if \(!sectionRoot \|\| !sections\.length\)/);
assert.match(site,/场景应用示意图｜AI生成/);
assert.match(site,/renderAuthorLicense/);
const css=fs.readFileSync(path.join(root,'styles.css'),'utf8');
assert.match(css,/@media \(max-width: 900px\)[\s\S]*\.gallery-grid \{ grid-template-columns: 1fr; \}/);
for(const item of sitting.gallery){assert.ok(fs.existsSync(path.join(root,item.src.replace(/^\.\//,''))));}
console.log('structured model detail focused tests: PASS');
